### PR TITLE
Update

### PR DESCRIPTION
**Pull request by DvDty**
https://www.reddit.com/r/PHP/comments/8pk5ps/small_vanilla_php_user_loginlogout_app/e0dseml/

### CODE REVIEW

**Comment by DvDty** [comment]
https://www.reddit.com/r/PHP/comments/8pk5ps/small_vanilla_php_user_loginlogout_app/e0dseml/

**Comment by halfer** [comment]
This looks like it has a lot of changes that could do with breaking down into smaller PRs, @DvDty. There's a mix of cosmetic, config and possibly features all melded together.

**Comment by DvDty** [comment]
Well, I just made the changes at once and there are 
very, very general, plus I don't want to PR something that is not working.

**Comment by halfer** [comment]
Sure @DvDty - my motivation for commenting is to observe that the point of the repo is to learn, so noting that there is a 'best practice' for PRs is probably worthwhile too. :slightly_smiling_face:

**Comment by taniarascia** [comment]
Sorry, I haven't gotten around to commenting on this PR, as I wanted to be able to comment on all the parts individually. First of all, @DvDty, thank you so much going through, organizing, and improving this! I learned so much just by looking at your end result and seeing how you got there.

I didn't want to just pull the PR, as I want to be able to understand each and every line of code I put into my app, and also there were some merge conflicts because I probably made edits between your original fork and the PR.

First, I learned about abstract classes from the Model and Controller classes, which was enlightening. Learning how to separate $_POST and $_GET into separate controller functions was also eye-opening for me, though I wonder how that will work with future iterations that AJAX/XHR via JavaScript instead of PHP posting to the same page.

I have some confusion about what belongs in a model and what belongs in a controller. If you look at my current iteration of the app, I have any function that queries the database in the model, based on the way you had it set up. I've heard conflicting opinions about whether or not that belongs in the model or controller.

This is my first time doing OOP and using classes, and it has been immensely helpful overall to be able to take my completely procedural above-the-fold PHP code and separate them into classes.

The current version of the app is functioning and all sections, including password resets, are running through functions in classes.

**Comment by taniarascia** [comment]
Thanks again for your insight! It really helped get me to the next level with this app. I'm going to close this PR now since the project has since progressed, but a lot of the concepts you introduced were used, such as abstract classes, the Model class, and making the controllers into classes.

**Pull request closed without merging**
